# Generated by Django 2.1.4 on 2019-01-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='a_content',
            field=models.TextField(null=True),
        ),
    ]
